version: "3"
services:
  server:
    build: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=db
      - PGUSER=momo
      - PGPASSWORD=12345
      - PGHOST=db
    depends_on:
      - db
      - redis

  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: momo
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    command: redis-server --appendonly yes

volumes:
  db_data: {}
  redis_data: {}
